### ISSUE TITLE
issue with launch file, specifically the ros2 control node

### ISSUE THREAD

**Issue by bryangd34** [alesof/ethercat_ROS2#2]
Good day,
Thanks a lot for a great repo, I am working with ZeroErr drivers, so this repo is awesome. I am currently facing this issue when I do `ros2 launch ethercat_zeroerr motor_drive.launch.py` :

[ros2_control_node-1] [INFO] [1729423875.705684492] [resource_manager]: Loading hardware 'ethercat_zeroerr'
[ros2_control_node-1] terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
[ros2_control_node-1]   what():  According to the loaded plugin descriptions the class ethercat_driver/EthercatDriver with base class type hardware_interface::SystemInterface does not exist. Declared types are  fake_components/GenericSystem mock_components/GenericSystem test_hardware_components/TestSystemCommandModes test_hardware_components/TestTwoJointSystem

Do you have any ideas why it might not be working? Thanks

**Comment by bryangd34** [comment]
Closing, was related to sourcing the ros2 workspaces for the same terminal.

**Comment by alesof** [comment]
Hi Bryan, glad you managed to solve this quickly! 

Feel free to suggest improvements and point out issues you encounter along the way using zeroerr with this ros2 setup. Of course if you want to directly contribute open issues and PRs. I'll be working again with this drives again in a few weeks. 

Have a nice day 👍🏼

**Comment by bryangd34** [comment]
Thanks @alesof . Will let you know how I get on and yes, will gladly contribute PRs.
